# Generated by Django 4.0.10 on 2025-01-19 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_customuser_id_alter_customuser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='birthday',
            field=models.DateField(default='2000-01-01'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customuser',
            name='school',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
