# Generated by Django 4.0.10 on 2024-10-11 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DormAccommodation',
            fields=[
                ('dorm_id', models.CharField(editable=False, max_length=10, primary_key=True, serialize=False, unique=True)),
                ('dorm_class', models.CharField(choices=[('A', 'Class A'), ('B', 'Class B')], max_length=1)),
                ('room_type', models.CharField(choices=[('Solo', 'Solo'), ('Shared', 'Shared')], max_length=6)),
                ('no_of_occupied', models.IntegerField()),
                ('occupied_status', models.CharField(choices=[('YES', 'Yes'), ('NO', 'No')], max_length=3)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('last_name', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=100)),
                ('suffix', models.CharField(blank=True, max_length=10, null=True)),
                ('birthday', models.DateField()),
                ('gender', models.CharField(choices=[('CF', 'Cisgender Female'), ('CM', 'Cisgender Male'), ('TM', 'Transgender Male'), ('TF', 'Transgender Female'), ('NB', 'Non-Binary')], max_length=2)),
                ('contact_number', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('school', models.CharField(max_length=255)),
                ('degree_program', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='BookingStatus',
            fields=[
                ('book_id', models.CharField(editable=False, max_length=10, primary_key=True, serialize=False, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('book_status', models.CharField(choices=[('Pending', 'Pending'), ('ForPayment', 'For Payment'), ('Paid', 'Paid')], max_length=10)),
                ('dorm_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dormmatch.dormaccommodation')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dormmatch.userprofile')),
            ],
        ),
    ]
