# Generated by Django 4.0.10 on 2025-01-19 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dormmatch', '0002_rename_user_id_userprofile_id_userprofile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='degree_program',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='first_name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(choices=[('CF', 'Cisgender Female'), ('CM', 'Cisgender Male'), ('TM', 'Transgender Male'), ('TF', 'Transgender Female'), ('NB', 'Non-Binary')], max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='last_name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='suffix',
            field=models.CharField(blank=True, choices=[('Jr', 'Jr.'), ('Sr', 'Sr.'), ('II', 'II'), ('III', 'III')], max_length=10, null=True),
        ),
    ]
