# Generated by Django 4.0.10 on 2025-01-22 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dormmatch', '0003_alter_userprofile_degree_program_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(choices=[('Cisgender Female', 'Cisgender Female'), ('Cisgender Male', 'Cisgender Male'), ('Transgender Male', 'Transgender Male'), ('Transgender Female', 'Transgender Female'), ('Non-Binary', 'Non-Binary')], max_length=20),
        ),
    ]
